//! Learner-facing content enrichment: a plain-language explanation
//! (คำอธิบายง่าย) and one example sentence per word.
//!
//! This is the **offline-precomputed** generative layer (AGENT_HANDOFF.md §1,
//! §7.5 P1). The text is produced ONCE, offline — either hand-authored
//! (`human_seed`) or generated by a Thai LLM run offline via the
//! `gen-learner` tool (`typhoon-2`/`sea-lion`) — then shipped as a static JSON
//! asset. **The running engine never calls an LLM.** If this text is imperfect
//! it cannot corrupt the formal definition or the explainable relationship
//! graph; it only enriches them, and its provenance is always labeled.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// One word's learner content.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LearnerContent {
    /// Plain-language explanation (คำอธิบายง่าย).
    pub simple: String,
    /// One natural example sentence.
    pub example: String,
    /// Honest provenance of THIS entry's text: "human_seed", "typhoon-2", …
    pub source: String,
}

/// Deserialization shape of the JSON asset (`{ "_meta": …, "entries": {…} }`).
#[derive(Debug, Deserialize)]
struct Asset {
    #[serde(default)]
    entries: HashMap<String, LearnerContent>,
}

/// A loaded store of learner content, keyed by headword.
#[derive(Debug, Clone, Default)]
pub struct LearnerStore {
    by_word: HashMap<String, LearnerContent>,
}

/// The default asset, embedded at compile time so the demo needs no external
/// file. Regenerate it offline with the `gen-learner` binary.
const DEFAULT_ASSET_JSON: &str = include_str!("../data/learner_content.json");

impl LearnerStore {
    /// Empty store (no enrichment).
    pub fn empty() -> Self {
        Self::default()
    }

    /// Parse a store from a JSON asset string.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let asset: Asset = serde_json::from_str(json)?;
        Ok(Self { by_word: asset.entries })
    }

    /// Load the built-in (compile-time-embedded) default asset. Falls back to an
    /// empty store if the embedded JSON somehow fails to parse (never panics —
    /// enrichment is optional).
    pub fn embedded() -> Self {
        Self::from_json(DEFAULT_ASSET_JSON).unwrap_or_default()
    }

    /// Look up learner content for a headword.
    pub fn get(&self, word: &str) -> Option<&LearnerContent> {
        self.by_word.get(word)
    }

    pub fn len(&self) -> usize {
        self.by_word.len()
    }

    pub fn is_empty(&self) -> bool {
        self.by_word.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_asset_parses_and_covers_seed_words() {
        let store = LearnerStore::embedded();
        // All 20 seed words should have learner content.
        assert!(store.len() >= 20, "expected >=20 learner entries, got {}", store.len());
        for w in ["แมว", "ครู", "อ่าน", "พจนานุกรม", "เขียน"] {
            let c = store.get(w).unwrap_or_else(|| panic!("missing learner content for {w}"));
            assert!(!c.simple.is_empty(), "empty simple for {w}");
            assert!(!c.example.is_empty(), "empty example for {w}");
            assert!(!c.source.is_empty(), "empty source for {w}");
        }
    }

    #[test]
    fn source_provenance_is_honest_label() {
        let store = LearnerStore::embedded();
        let known = ["human_seed", "typhoon-2", "sea-lion"];
        for w in ["แมว", "ครู"] {
            let c = store.get(w).unwrap();
            assert!(
                known.contains(&c.source.as_str()),
                "unexpected provenance label '{}' for {w}",
                c.source
            );
        }
    }

    #[test]
    fn unknown_word_has_no_content() {
        let store = LearnerStore::embedded();
        assert!(store.get("ไดโนเสาร์").is_none());
    }

    #[test]
    fn empty_store_returns_none() {
        let store = LearnerStore::empty();
        assert!(store.get("แมว").is_none());
        assert!(store.is_empty());
    }
}
