//! วาจา (WACHA) offline WASM build — Round 6, Phase W (flagship).
//!
//! The whole modelless engine (Datrie segmenter + explainable relationship
//! graph with provenance/confidence) compiled to WebAssembly and run **in the
//! browser tab** — no backend, no GPU, no network after first load. This is the
//! "modelless / deterministic / explainable" thesis made physical: a judge can
//! open it on their phone, turn on airplane mode, and it still works.
//!
//! **Raw `extern "C"` ABI, not wasm-bindgen.** The unattended build box has no
//! `wasm-bindgen` CLI; rather than block on installing tooling, we expose a
//! tiny hand-written ABI (alloc / dealloc / segment / lookup) callable directly
//! from JS via the browser's `WebAssembly` API + a `Uint8Array` view over the
//! module's linear memory. Fewer moving parts, self-contained, and verifiable
//! with plain `node`. (A wasm-bindgen wrapper is a drop-in future nicety.)
//!
//! **Reduced dataset (stop rule W).** The full engine also merges an 82 MB
//! Kaikki JSONL — far over the ~25 MB WASM budget. This build ships the
//! **segmenter (62k CC0 words) + hand-verified seed relations + embedded Thai
//! WordNet synonyms** only; it does NOT include the 29k Kaikki definitions. So
//! in-browser you get full Thai segmentation and explainable WordNet/seed
//! relationships, but definitions only for the seed words. The UI says so
//! plainly. Adding the Kaikki layer is the Phase-M footprint work (front-coded
//! dictionary blob) — deliberately out of scope for this build.

use std::cell::RefCell;
use wacha::Engine;

// The 62k CC0 LEXiTRON word list, embedded so the segmenter needs no fetch.
// (~1.5 MB of Thai text; compresses well.)
const WORDS_TH: &str = include_str!("../../data/words_th.txt");

// Prebuilt segmenter trie cache for the reduced (words_th + seed) vocab, so the
// browser skips the ~200 s cold trie build entirely and is interactive in ~ms.
// Generated natively by `wacha/examples/gen_reduced_cache.rs`.
const SEG_CACHE: &[u8] = include_bytes!("../assets/words_th.seg");

// Compact definitions blob (W2): all 29,601 defined headwords + primary
// definition, sorted by headword, binary-searchable, NO JSON at runtime.
// Format: [u32 count] then count × [u16 hw_len][hw][u16 def_len][def][u8 src].
// Generated natively by `wacha/examples/gen_defs_blob.rs`.
const DEFS_BLOB: &[u8] = include_bytes!("../assets/defs.blob");

// Reverse-dictionary index (Phase C): the BM25 inverted index over segmented
// definitions, prebuilt natively and postcard-serialised so the browser does
// reverse lookup offline without rebuilding. Generated by
// `wacha/examples/gen_reverse_index.rs`.
const REVERSE_IDX: &[u8] = include_bytes!("../assets/reverse.idx");

thread_local! {
    static ENGINE: RefCell<Option<Engine>> = const { RefCell::new(None) };
    // (headword, definition, src_code, examples)
    static DEFS: RefCell<Option<Vec<(String, String, u8, Vec<String>)>>> = const { RefCell::new(None) };
    static REVERSE: RefCell<Option<wacha::reverse::ReverseIndex>> = const { RefCell::new(None) };
}

/// Parse the embedded defs blob into a sorted (headword, def, src, examples)
/// table. Format v2 (W2 + L1):
///   [u32 count] then count × [u16 hw_len][hw][u16 def_len][def][u8 src]
///                            [u16 ex_len][ex]  -- examples joined by \x1f
fn parse_defs() -> Vec<(String, String, u8, Vec<String>)> {
    let b = DEFS_BLOB;
    let mut out = Vec::new();
    if b.len() < 4 {
        return out;
    }
    let count = u32::from_le_bytes([b[0], b[1], b[2], b[3]]) as usize;
    let mut p = 4usize;
    for _ in 0..count {
        if p + 2 > b.len() { break; }
        let hl = u16::from_le_bytes([b[p], b[p + 1]]) as usize; p += 2;
        if p + hl > b.len() { break; }
        let hw = String::from_utf8_lossy(&b[p..p + hl]).into_owned(); p += hl;
        if p + 2 > b.len() { break; }
        let dl = u16::from_le_bytes([b[p], b[p + 1]]) as usize; p += 2;
        if p + dl > b.len() { break; }
        let def = String::from_utf8_lossy(&b[p..p + dl]).into_owned(); p += dl;
        if p >= b.len() { break; }
        let src = b[p]; p += 1;
        if p + 2 > b.len() { break; }
        let el = u16::from_le_bytes([b[p], b[p + 1]]) as usize; p += 2;
        if p + el > b.len() { break; }
        let ex_joined = String::from_utf8_lossy(&b[p..p + el]).into_owned(); p += el;
        let examples: Vec<String> = if ex_joined.is_empty() {
            Vec::new()
        } else {
            ex_joined.split('\u{1f}').map(|s| s.to_string()).collect()
        };
        out.push((hw, def, src, examples));
    }
    out
}

fn src_label(code: u8) -> &'static str {
    match code {
        0 => "ตรวจด้วยมือ",
        1 => "Kaikki (Wiktionary)",
        2 => "ศัพท์บัญญัติ (ORST)",
        3 => "RID ๒๕๕๔ (ORST)",
        _ => "",
    }
}

/// Look up a definition (definition, source, examples) from the embedded blob
/// by binary search. Returns None if not defined.
fn lookup_def(word: &str) -> Option<(String, String, Vec<String>)> {
    DEFS.with(|cell| {
        let mut opt = cell.borrow_mut();
        if opt.is_none() {
            *opt = Some(parse_defs());
        }
        let defs = opt.as_ref().unwrap();
        defs.binary_search_by(|(hw, _, _, _)| hw.as_str().cmp(word))
            .ok()
            .map(|i| {
                let d = &defs[i];
                (d.1.clone(), src_label(d.2).to_string(), d.3.clone())
            })
    })
}

fn with_engine<R>(f: impl FnOnce(&Engine) -> R) -> R {
    ENGINE.with(|cell| {
        let mut opt = cell.borrow_mut();
        if opt.is_none() {
            // Load the prebuilt segmenter from the embedded cache (no trie
            // build, no fs, no network); seed entries + embedded WordNet drive
            // relations. Falls back to building from words if the cache is
            // somehow unreadable (should never happen — it's compiled in).
            let words: Vec<&str> = WORDS_TH.lines().filter(|l| !l.trim().is_empty()).collect();
            let entries = wacha::dictionary::seed_entries();
            let eng = match wacha::segmenter::Segmenter::from_cache_bytes(SEG_CACHE) {
                Ok(seg) => Engine::build_from_segmenter(words, entries, None, seg),
                Err(_) => Engine::build(words, entries, None),
            };
            *opt = Some(eng);
        }
        f(opt.as_ref().unwrap())
    })
}

// ── Raw ABI ──────────────────────────────────────────────────────────────────

/// Allocate `len` bytes in the module's linear memory; returns a pointer the JS
/// side writes the query bytes into.
#[no_mangle]
pub extern "C" fn wacha_alloc(len: usize) -> *mut u8 {
    let mut buf = Vec::<u8>::with_capacity(len);
    let ptr = buf.as_mut_ptr();
    std::mem::forget(buf);
    ptr
}

/// Free a buffer previously returned by `wacha_alloc` / a result buffer.
#[no_mangle]
pub extern "C" fn wacha_free(ptr: *mut u8, len: usize) {
    if !ptr.is_null() && len > 0 {
        unsafe {
            drop(Vec::from_raw_parts(ptr, 0, len));
        }
    }
}

/// Force-build the engine now (so JS can show a spinner during the one-time
/// build) and return the searchable word count as a readiness signal.
#[no_mangle]
pub extern "C" fn wacha_init() -> u32 {
    with_engine(|e| e.word_count() as u32)
}

/// Segment `query` (UTF-8 at ptr/len). Returns a pointer to a length-prefixed
/// result buffer: `[u32 little-endian json_len][json_len bytes of UTF-8 JSON]`.
/// JS reads the length, copies the JSON, then calls `wacha_free(ptr, 4+len)`.
#[no_mangle]
pub extern "C" fn wacha_segment(ptr: *const u8, len: usize) -> *mut u8 {
    let query = read_str(ptr, len);
    let json = with_engine(|e| {
        let toks = e.segment(&query);
        let mut s = String::from("[");
        for (i, t) in toks.iter().enumerate() {
            if i > 0 { s.push(','); }
            s.push_str(&format!("{{\"text\":{},\"in_vocab\":{}}}", json_str(&t.text), t.in_vocab));
        }
        s.push(']');
        s
    });
    pack(&json)
}

/// Look up `query`; returns length-prefixed JSON (same envelope as segment):
/// `{ "query", "segmentation":[…], "entry":{…}|null, "related":[…] }`.
#[no_mangle]
pub extern "C" fn wacha_lookup(ptr: *const u8, len: usize) -> *mut u8 {
    let query = read_str(ptr, len);
    let json = with_engine(|e| lookup_json(e, &query));
    pack(&json)
}

/// Reverse dictionary (Phase C): find headwords by describing their meaning.
/// Returns length-prefixed JSON: `{ "query", "hits":[{word,score,matched[]}] }`.
#[no_mangle]
pub extern "C" fn wacha_reverse(ptr: *const u8, len: usize) -> *mut u8 {
    let query = read_str(ptr, len);
    let json = reverse_json(&query);
    pack(&json)
}

fn reverse_json(query: &str) -> String {
    let hits = REVERSE.with(|cell| {
        let mut opt = cell.borrow_mut();
        if opt.is_none() {
            *opt = Some(postcard::from_bytes(REVERSE_IDX).expect("reverse.idx"));
        }
        let idx = opt.as_ref().unwrap();
        with_engine(|e| idx.search(query, 8, |s| e.segment_words(s)))
    });
    let mut s = String::from("{");
    s.push_str(&format!("\"query\":{},\"hits\":[", json_str(query)));
    for (i, h) in hits.iter().enumerate() {
        if i > 0 { s.push(','); }
        s.push_str(&format!("{{\"word\":{},\"score\":{:.4},\"matched\":{}}}",
            json_str(&h.word), h.score, json_arr(&h.matched)));
    }
    s.push_str("]}");
    s
}

// ── helpers ────────────────────────────────────────────────────────────────

fn read_str(ptr: *const u8, len: usize) -> String {
    if ptr.is_null() || len == 0 {
        return String::new();
    }
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    String::from_utf8_lossy(bytes).into_owned()
}

/// Pack a string into a freshly-allocated `[u32 len][bytes]` buffer, leak it,
/// return the pointer. JS frees via `wacha_free(ptr, 4 + len)`.
fn pack(s: &str) -> *mut u8 {
    let body = s.as_bytes();
    let mut buf = Vec::<u8>::with_capacity(4 + body.len());
    buf.extend_from_slice(&(body.len() as u32).to_le_bytes());
    buf.extend_from_slice(body);
    let ptr = buf.as_mut_ptr();
    std::mem::forget(buf);
    ptr
}

fn lookup_json(engine: &Engine, query: &str) -> String {
    let r = engine.lookup(query, 8);
    let mut s = String::from("{");
    s.push_str(&format!("\"query\":{},", json_str(query)));
    s.push_str("\"segmentation\":[");
    for (i, t) in r.segmentation.iter().enumerate() {
        if i > 0 { s.push(','); }
        s.push_str(&format!("{{\"text\":{},\"in_vocab\":{}}}", json_str(&t.text), t.in_vocab));
    }
    s.push_str("],");
    match &r.entry {
        Some(e) => s.push_str(&format!(
            "\"entry\":{{\"word\":{},\"pos\":{},\"definition\":{},\"source\":{},\"license\":{},\"examples\":{}}},",
            json_str(&e.word), json_str(&e.pos), json_str(&e.definition),
            json_str(&e.source), json_str(&e.license), json_arr(&e.examples)
        )),
        None => {
            // W2: the segmenter engine only carries the 20 seed entries in the
            // WASM build, but the embedded defs blob has all 29,601. If the
            // query is a single defined headword, serve the blob definition
            // (+ L1 usage examples).
            match lookup_def(query.trim()) {
                Some((def, src, examples)) => s.push_str(&format!(
                    "\"entry\":{{\"word\":{},\"pos\":{},\"definition\":{},\"source\":{},\"license\":{},\"examples\":{}}},",
                    json_str(query.trim()), json_str(""), json_str(&def), json_str(&src), json_str(""), json_arr(&examples)
                )),
                None => s.push_str("\"entry\":null,"),
            }
        }
    }
    s.push_str("\"related\":[");
    for (i, rw) in r.related.iter().enumerate() {
        if i > 0 { s.push(','); }
        s.push_str(&format!(
            "{{\"word\":{},\"score\":{:.4},\"source\":{},\"confidence\":{},\"path\":[",
            json_str(&rw.word), rw.score, json_str(rw.source.as_str()), json_str(rw.confidence.as_str())
        ));
        for (j, edge) in rw.path.iter().enumerate() {
            if j > 0 { s.push(','); }
            s.push_str(&json_str(edge));
        }
        s.push_str("]}");
    }
    s.push_str("]}");
    s
}

fn json_arr(items: &[String]) -> String {
    let mut out = String::from("[");
    for (i, it) in items.iter().enumerate() {
        if i > 0 { out.push(','); }
        out.push_str(&json_str(it));
    }
    out.push(']');
    out
}

fn json_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
